### ISSUE TITLE
Cannot deploy to private repository with STS credentials

### ISSUE THREAD

**Issue by dball** [technomancy/s3-wagon-private#30]
I cannot deploy my projects to a private repository. When I try, it reports:

```
Could not transfer metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml from/to private (s3p://my-private-bucket/releases/): Access Denied
Failed to retrieve remote metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml from/to private (s3p://my-private-bucket/releases/): Access Denied
```

If I run with DEBUG, I get the following interesting stacktrace snippet:

```
Caused by: AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 3540C63CD5572DE0, AWS Error Code: AccessDenied, AWS Error Message: Access Denied, S3 Extended Request ID: PfWFRjrE3ddszMbOgz+xVI5Ey3kSW2/LPzceFrHJLGqp/W8bfUEiUKTWVap/pOOESWA2UPT3dOQ=
       	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:644)
       	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:338)
       	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:190)
       	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2985)
       	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2956)
       	at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:548)
       	at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:556)
       	at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:99)
```

I have verified that the account in question has the correct s3 permissions on the relevant bucket.

**Comment by danielcompton** [comment]
It looks quite likely that this is an IAM permissions problem. Are you able to temporarily give that IAM account admin or full S3 permissions, to check whether the permissions are setup ok? Also, can you post your (redacted) IAM policy here?

**Comment by dball** [comment]
The account does have full S3 permissions, both wildcard and enumerated. I suspect that the correct values simply are not being threaded through for some reason. Is there a super-verbose mode by any chance that could help in debugging?

**Comment by danielcompton** [comment]
Perhaps something like this? http://stackoverflow.com/questions/24310889/how-to-redirect-aws-sdk-logging-output

Can you share what your `:repositories` config is?

**Comment by dball** [comment]
Sure:

```  :repositories [["snapshot" {:url "s3p://maven.sparkfund.co/snapshots/"
                              :username :env/aws_access_key_id
                              :password :env/aws_secret_access_key}]]```

When I try to use it:

```
~/src/banks[s3-wagon]$ lein deploy snapshot
WARNING: please set :license in project.clj.
Created /Users/dball/src/banks/target/banks-0.1.1-SNAPSHOT.jar
Wrote /Users/dball/src/banks/pom.xml
Could not transfer metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml from/to snapshot (s3p://maven.sparkfund.co/snapshots/): Access Denied
Failed to retrieve remote metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata banks:banks:0.1.1-SNAPSHOT/maven-metadata.xml from/to snapshot (s3p://maven.sparkfund.co/snapshots/): Access Denied
```

But the env var credentials really are good:

```
~/src/banks[s3-wagon]$ aws s3 ls s3://maven.sparkfund.co/snapshots/
                           PRE banks/
2016-08-15 22:39:03          0
```

**Comment by dball** [comment]
FWIW the mechanism by which the credentials are given seems to have no effect: env vars, string literals, stdin, I always get the same 403 forbidden trying to get-bucket-location, though the operation succeeds using the aws cli with the same credentials.

Very much looks like a bug threading the values downstream to the AmazonHttpClient, but... this seems like basic, bog-standard functionality; it'd be hard to believe I'm the first lucky user to have experienced this, so I must be doing something wrong.

**Comment by dball** [comment]
PEBCAK: `:password` and `:passphrase` are not the same thing. Correcting the keyword fixes this problem.

I do still have a problem using s3-wagon-private with aws-vault, which generates temporary credentials using STS and providing them as env vars. It fails similarly, but somewhat differently:

```Caused by: AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: AFA61976C51FBE57, AWS Error Code: InvalidAccessKeyId, AWS Error Message: The AWS Access Key Id you provided does not exist in our records., S3 Extended Request ID: AFDdSSeO24jBPqmpzxhWAxb54/n9AMpeEXM6WvpXAM7Pnx74whTcwf+OGIRfY4v2a6w9V5qd0UQ=```

The correct `:username` and `:passphrase` are being used. Again, the AWS cli succeeds.

**Comment by dball** [comment]
The problem seems to be far downstream in aws-java-sdk, actually. Versions prior to 1.8.0 do not seem to work with AWS STS credentials, while subsequent versions do. I opened an issue with aws-maven: https://github.com/spring-projects/aws-maven/issues/49

**Comment by danielcompton** [comment]
I've bumped the aws-java-sdk version to `1.11.28` and released https://clojars.org/s3-wagon-private/versions/1.3.0-SNAPSHOT. Can you try again with this version and let me know how you get on? Thanks!

**Comment by dball** [comment]
Alas, it does not work due to a jackon version mismatch, apparently:

```Exception in thread "pool-11-thread-1" Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
       	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1529)
       	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:167)
       	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:132)
       	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
       	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
       	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
       	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
       	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
       	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
       	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
       	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
       	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2679)
       	at com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:236)
       	at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:249)
       	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
       	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:141)
       	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:136)
       	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:97)
       	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:60)
       	at org.springframework.build.aws.maven.S3Utils.getClientConfiguration(S3Utils.java:45)
       	at org.springframework.build.aws.maven.PrivateS3Wagon.connectToRepository(PrivateS3Wagon.java:92)
       	at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:143)
       	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:345)
       	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon(WagonRepositoryConnector.java:385)
       	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:571)
       	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)```

**Comment by danielcompton** [comment]
Sorry, I didn't hit this in my testing. Will try and get an `aws-vault` setup so I can do some more testing myself. The problem was that I didn't exclude the aws-java-sdk from the spring aws-maven project (which seems basically abandoned).

I can fix the deps conflict, but it's probably better long term to move to this fork which is maintained https://github.com/Yleisradio/aws-maven

**Comment by danielcompton** [comment]
Can you share what your `:repositories` config looks like when using aws-vault?

**Comment by dball** [comment]
Sure:

```  :repositories [["snapshot" {:url "s3p://maven.mydomain/snapshots/"
                              :username :env/aws_access_key_id
                              :passphrase :env/aws_secret_access_key}]])```

**Comment by dball** [comment]
Yeah, I looked at that aws-maven fork as well. One thing that gave me pause was that it seems to have its own leiningen repo protocol registry stuff going on:

https://github.com/Yleisradio/aws-maven/blob/master/src/main/resources/leiningen/wagons.clj

which may or may not collide with this plugin's? I confess I'm only guessing as to how this stuff works under the hood, but if two projects are contending for the same entry in a global registry, it's not going to work out well.

**Comment by danielcompton** [comment]
Yeah I noticed that too which was interesting ...

It shouldn't conflict as we're registering for `s3p`, but worth keeping an eye out for.

**Comment by danielcompton** [comment]
Here's my findings:

To use STS tokens, you need another environment variable: `AWS_SESSION_TOKEN` the access key id and secret access key alone aren't enough to authenticate. That's why older versions of the AWS deps don't work. [More details](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs)

Can you explain how you are triggering `aws-vault` to generate the STS tokens? I'm guessing it's something like `aws-vault exec default -- lein deps`. Is that correct?

I'm thinking that the way that credentials are provided needs to be rethought a little bit to support modern AWS usage, however I'm not really sure how `aws-vault` should integrate with this, as it's a separate tool that needs to be invoked so that a child process can access the environment variables. One option would be to exfiltrate the AWS env vars to the parent process, but I'm not really sure.

**Comment by danielcompton** [comment]
I've spent a chunk of time on this, and wasn't able to get the dependencies to play nice. @dball I think the easiest way forward if you're still interested in this is for you to provide a PR which works for you, and I'm happy to merge it. Does that work?

**Comment by dball** [comment]
Absolutely, that's more than fair. Thanks for investigating!

**Comment by danielcompton** [comment]
@dball have you tried with the new alpha releases? Do they solve your problem?

**Comment by dball** [comment]
Ah, no, was not aware. I wrote an aws cli maven to sidestep the problem, but will try out the alphas at my earliest convenience.
